#!/usr/bin/env bash
set -e

# Install build dependencies
apt-get update -qq
apt-get install -y --no-install-recommends \
    build-essential \
    make \
    gcc \
    libglpk-dev \
    openmpi-bin \
    libopenmpi-dev
rm -rf /var/lib/apt/lists/*
