#!/usr/bin/env bash
set -e

# Install build dependencies
apt-get update -qq
apt-get install -y --no-install-recommends \
    build-essential \
    libglpk-dev \
    openmpi-bin \
    libopenmpi-dev \
    > /dev/null
rm -rf /var/lib/apt/lists/*
